For review
cdkrot/inter-message pull request #1
Opened 2017-12-20 08:03 UTC by studentfedorov

2017-12-20 15:48 UTC, dzharkov requested changes
В целом, довольно неприятное впечатление пока.
Жду изменений и ответов на вопросы. 
Желательно написать на почту, как будет готово

2017-12-20 15:48 UTC, dzharkov commented on app/src/main/java/ru/spbau/intermessage/core/Messenger.java
> +                    System.out.printf("Incoming packet from %s, type %d, len %d\n", from, (bcast ? 1 : 0), dta.size());
` System.out.*`, куча закоменченного кода наводит на мысль, что вы не особо готовились к ревью :(

2017-12-20 15:48 UTC, dzharkov commented on app/src/main/java/ru/spbau/intermessage/Controller.java
> +        if (intent != null) {
Может наоборот лучше `if (intent == null) return;`?

2017-12-20 15:48 UTC, dzharkov commented on app/src/main/java/ru/spbau/intermessage/Controller.java
> +            final String action = intent.getAction();
Можете пояснить, как вы выбираете делать ли локальную переменную final?

2017-12-20 15:48 UTC, dzharkov commented on app/src/main/java/ru/spbau/intermessage/Controller.java
> +        intent.putExtra("User", "Dima");
Это ок, что здесь это захардкожено?

2017-12-20 15:48 UTC, dzharkov commented on app/src/main/java/ru/spbau/intermessage/Controller.java
> +    public static void receiveMessage(Context context, User chat, ru.spbau.intermessage.core.Message message) {
Я бы переименовал свой класс `Message`, чтобы не было вот таких страданий

2017-12-20 15:48 UTC, dzharkov commented on app/src/main/java/ru/spbau/intermessage/DialogActivity.java
> +        if (id == R.id.nav_camera) {
switch?

2017-12-20 15:48 UTC, dzharkov commented on app/src/main/java/ru/spbau/intermessage/DialogActivity.java
> +        if (messageReceiver != null)
Код не соответствует Java code conventions, много где не хватает фигурных скобок

2017-12-20 15:48 UTC, dzharkov commented on app/src/main/java/ru/spbau/intermessage/core/Message.java
> +    public String type;
Публичные поля тоже так себе подход

2017-12-20 15:48 UTC, dzharkov commented on app/src/main/java/ru/spbau/intermessage/gui/Message.java
> +public class Message {
Ну вот два класса с одинаковым именем в проекте -- это какой-то адок совсем

2017-12-20 15:48 UTC, dzharkov commented on app/src/main/java/ru/spbau/intermessage/util/ByteVector.java
> +public class ByteVector {
А в стандартное библиотеке Java точно нет ничего, что могло бы нас спасти от изобретения велосипедов?

2017-12-20 15:48 UTC, dzharkov commented on app/src/main/java/ru/spbau/intermessage/net/WifiNetwork.java
> + * It is recommended to don't read this class for kids, sensitive people, and all others.
О, еще одна шутеечка!

2017-12-20 15:48 UTC, dzharkov commented on app/src/main/java/ru/spbau/intermessage/net/WifiNetwork.java
> + * Live a healthy life, stay away from java.
По делу: я бы все-таки хотел понять, в чем идея вашего проекта и почему вы используете настолько низкоуровневые вещи, как самодельные UDP/TCP протоколы?

2017-12-20 16:06 UTC, studentfedorov commented on app/src/main/java/ru/spbau/intermessage/Controller.java
> +    public static void receiveMessage(Context context, User chat, ru.spbau.intermessage.core.Message message) {
Да, в целом, я уже давно хотел это сделать, но пока не выбрал имя для нового класса

2017-12-20 16:08 UTC, studentfedorov commented on app/src/main/java/ru/spbau/intermessage/Controller.java
> +        intent.putExtra("User", "Dima");
Это я пока не смог понять, откуда мне брать имя пользователя. Я верю, что когда-нибудь Дима добавит куда-нибудь  возможность получать имя пользователя/диалога

2017-12-20 16:09 UTC, studentfedorov commented on app/src/main/java/ru/spbau/intermessage/Controller.java
> +        if (intent != null) {
Не вижу большой разницы, но ладно

2017-12-20 16:14 UTC, studentfedorov commented on app/src/main/java/ru/spbau/intermessage/Controller.java
> +            final String action = intent.getAction();
Скорее всего, как-то случайно попало...

2017-12-20 16:17 UTC, studentfedorov commented on app/src/main/java/ru/spbau/intermessage/core/Message.java
> +    public String type;
Почему? 
Писать геттеры/сеттеры для класса, который я использую только для хранения объектов, мне не кажется хорошей идеей

2017-12-20 16:27 UTC, studentfedorov commented on app/src/main/java/ru/spbau/intermessage/core/Messenger.java
> +                    System.out.printf("Incoming packet from %s, type %d, len %d\n", from, (bcast ? 1 : 0), dta.size());
Тут может быть моя вина, что я не предупредил Диму, что сегодня уже у нас что-то будут ревьювить.
У него есть еще ветка c уже более продвинутой сетью.

Вообще, конечно, мы к ревью не готовились, т.к. еще даже не весь проект закончен.
Но какой-то отзыв на то, что уже есть, хотелось получить...

2017-12-20 17:30 UTC, dzharkov commented on app/src/main/java/ru/spbau/intermessage/Controller.java
> +        if (intent != null) {
Разная глубина вложенности содержательной части кода. В некоторых компаниях вообще есть ограничения на максимальную вложенность, так как это ухудшает читаемость

2017-12-20 17:31 UTC, dzharkov commented on app/src/main/java/ru/spbau/intermessage/Controller.java
> +            final String action = intent.getAction();
Давайте во всех местах будет одинаково

2017-12-20 17:33 UTC, dzharkov commented on app/src/main/java/ru/spbau/intermessage/core/Message.java
> +    public String type;
Про это можно много где почитать. Например https://dzone.com/articles/getter-setter-use-or-not-use-0

Но, в целом, публичные поля в большинстве случаев запрещаются всеми разумными coding conventions

2017-12-20 17:36 UTC, dzharkov commented on app/src/main/java/ru/spbau/intermessage/core/Messenger.java
> +                    System.out.printf("Incoming packet from %s, type %d, len %d\n", from, (bcast ? 1 : 0), dta.size());
В первую очередь хочется понять, что у вас за приложение (со скриншотами желательно) и какое-то высокоуровневое описание архитектуры

2017-12-20 18:19 UTC, studentfedorov commented on app/src/main/java/ru/spbau/intermessage/core/Messenger.java
> +                    System.out.printf("Incoming packet from %s, type %d, len %d\n", from, (bcast ? 1 : 0), dta.size());
Мне кажется большинство ответов (например, архитектура и идея) есть здесь 
http://mit.spbau.ru/sewiki/index.php/InterMessage

2017-12-20 18:19 UTC, studentfedorov commented on app/src/main/java/ru/spbau/intermessage/core/Messenger.java
> +                    System.out.printf("Incoming packet from %s, type %d, len %d\n", from, (bcast ? 1 : 0), dta.size());
![image](https://user-images.githubusercontent.com/22048080/34222096-72857f02-e5cb-11e7-8829-cf28bd76721e.png)

2017-12-21 20:52 UTC, studentfedorov commented on app/src/main/java/ru/spbau/intermessage/core/Messenger.java
> +                    System.out.printf("Incoming packet from %s, type %d, len %d\n", from, (bcast ? 1 : 0), dta.size());
Немножко мотивации нашего проекта:
Ситуация А:
Вы школьник и поехали в летний лагерь под Кострому, а там нет интернета, но есть общая сеть wi-fi. Тогда чтобы общаться можно будет воспользоваться мессенджером для которого не нужен ни сервер, ни выход в интернет.

Ситуация Б:
Вы грибник и поехали группой за грибами в тайгу, а там нет ни Интернета ни общей сети wi-fi. Но вы не промах и взяли с собой мощный wi-fi роутер.
Тогда, чтобы сообщить другим людям, что вы нашли грибную поляну, вам теперь не нужно идти искать их в лесу, надеясь, что поляну за это время не найдут другие грибники.

2017-12-23 20:27 UTC, cdkrot commented on app/src/main/java/ru/spbau/intermessage/util/ByteVector.java
> +public class ByteVector {
Казалось бы есть ArrayList<Byte>, но это кошмар на каждый байт создавать свой объект.

2017-12-23 20:28 UTC, cdkrot commented on app/src/main/java/ru/spbau/intermessage/net/WifiNetwork.java
> + * Live a healthy life, stay away from java.
Мы пишем мессенджер без центрального сервера, подразумевается, что сообщения доставляется через локальную сеть по wifi.

Не очень понятно как обойтись без рукописного сетевого кода поэтому.

2017-12-24 21:06 UTC, closed without merging